### ISSUE TITLE
不喜欢 cleanMyMac 5.x 的 SetApp 用户，可以这么做

### ISSUE THREAD

**Issue by tobemaster56** [tobemaster56/draft#146]
对于一个使用了多年的SetAPP 的 Mac 用户来说，突然有一天，重新打开 cleanMyMac 之后，完全大变样，当然官方各种自夸，推上也有不少用户夸赞新的大版本漂亮。

但是对于我而言，cleanMyMac 就是个工具类的应用，花了那么多心思，搞的花里胡哨，我就不说了，改交互也算了，砍功能什么鬼，性能变差。关键是才突然意识到， setApp上所有的应用都是强制升级的。 

我看了推上也有一些用户抱怨，但是有啥用呢？我就给官方发邮件，明确要求给我降级使用cleanMyMac 4.x的方式。等了，2,3天后，今天终于给我搞定了。

解决方案，给我一个邀请链接，注册 MacPaw 账号，里面给了一个 cleanMyMac 4.x 的授权

![image](https://github.com/user-attachments/assets/0c19eb2c-9990-4bc9-9608-865d4ab1a04b)

**Comment by tobemaster56** [comment]
以下是邮件交流内容

![image](https://github.com/user-attachments/assets/8396354a-f640-4ee3-bb72-0c5041492676)

**Comment by tobemaster56** [comment]
官方邮件的回复基本上都是套话，像是【你的邮件我们已经收到了，请耐心等待之类的】，后面的邮件里提到，要是非常着急的话，可以线上聊天啥的。

https://macpaw.app/chat

还是直接线上聊天干脆点

![image](https://github.com/user-attachments/assets/34116f86-ca7d-4d8e-9a71-84d38584f9d4)

**Comment by jochne** [comment]
是只给了1年的授权吗？

**Comment by tobemaster56** [comment]
它这个是 macpaw 账号，订阅制的，一年后，如果不能用了，我继续喷他们

**Comment by tobemaster56** [comment]
1 年之后，提示我到期了，让我添加支付方式。

<img width="1044" height="1094" alt="Image" src="https://github.com/user-attachments/assets/5caff890-27b8-41cd-af81-5bf1b538d9e4" />

然后我回复，我就是想用  cleanMyMac X 4.x，一开始都是用机器人自动回复邮件。后面又人工回复我，给了我新的方案。
下面是官方的完整回复

<img width="2964" height="1492" alt="Image" src="https://github.com/user-attachments/assets/5d2c3918-1357-4835-970d-07f5a0770597" />

邮件中的链接

1. 卸载通过网页版下载的 cleanMyMac x 的工具
https://macpaw.zendesk.com/attachments/token/a1hmrddt42tl3DHAt7NlNJTjc/?name=Uninstall_CMMX.zip

2. cleanMyMac X 4.x 的 setApp 版本
https://store.setapp.com/app/78/40396/app-1727704072-66faac08421f2.zip

**Comment by tobemaster56** [comment]
我喜欢的 cleanMyMac X 又回来了

<img width="2258" height="1302" alt="Image" src="https://github.com/user-attachments/assets/c3df8bdf-50d9-4018-997b-093d4f3ec91a" />

**Comment by tobemaster56** [comment]
没想到，这个 setApp 的 cleanMyMacX，还是会自动升级到 cleanMyMac 5.x，后面又和官方沟通，最终还是给了我一个 cleanMyMacX 的永久网络版。这下终于彻底解决了。

<img width="2428" height="514" alt="Image" src="https://github.com/user-attachments/assets/826ec953-4971-4cea-88fe-6c0b4c4d38d5" />
